Add dogs list page
cvalera18/doggos pull request #4
Opened 2020-04-07 19:29 UTC by cvalera18

Dogs list page

2020-04-08 22:04 UTC, jmcaldera requested changes

2020-04-08 22:04 UTC, jmcaldera commented on app/build.gradle
> +    implementation 'androidx.cardview:cardview:1.0.0'
Para mejor legibilidad es mejor mantener un orden para las dependencias. Todos los `implementation` "juntos" y al final los `testImplementation` y `androidTestImplementation`

2020-04-08 22:04 UTC, jmcaldera commented on app/src/main/java/com/cvalera/doggos/MainActivity.java
> +    RecyclerView recyclerDogs;
`private RecyclerView recyclerDogs;`

2020-04-08 22:04 UTC, jmcaldera commented on app/src/main/java/com/cvalera/doggos/MainActivity.java
> +        AdaptadorDogs adapter = new AdaptadorDogs(listaDogs);
`listaDogs` no tiene otro uso a parte de pasarlo al constructor. Se puede eliminar `listaDogs` por completo y crear el adapter así: 
`AdaptadorDogs adapter = new AdaptadorDogs(new ArrayList<>());`

2020-04-08 22:04 UTC, jmcaldera commented on app/src/main/java/com/cvalera/doggos/data/Repository.java
>                  }
Qué pasa si `dogList` (`response.body()`) es null? Se tendría que notificar el error, algo así:

```
else {
  listener.onFailure("Body is null", null);
}
```

2020-04-08 22:04 UTC, jmcaldera commented on app/src/main/java/com/cvalera/doggos/model/AdaptadorDogs.java
> +
`icStar` = ???

2020-04-08 22:04 UTC, jmcaldera commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/rv1"
Asigna un id que haga referencia al contenido que muestra. Por ejemplo: 
`android:id="@+id/rv_dogs"`  or  `android:id="@+id/list_dogs"`

2020-04-08 22:04 UTC, jmcaldera commented on app/src/main/res/layout/item_list_dogs.xml
> +        android:layout_width="wrap_content"
No debería ser `0dp`  (match_constraint) en este caso para que ocupe el ancho del padre? Ya que estás definiendo `app:layout_constraintEnd_toEndOf="parent"` y `app:layout_constraintStart_toStartOf="parent"`

2020-04-08 22:04 UTC, jmcaldera commented on app/src/main/res/layout/item_list_dogs.xml
> +        android:layout_width="409dp"
0dp o match_parent

2020-04-08 22:04 UTC, jmcaldera commented on app/src/main/res/layout/item_list_dogs.xml
> +        android:layout_marginTop="5dp"
Utiliza dimension que sean al menos múltiplos de 4 u 8. En este caso podría ser 4dp u 8dp como mínimo. Lo recomendado sería 16dp.
https://material.io/design/layout/spacing-methods.html

2020-04-08 22:04 UTC, jmcaldera commented on app/src/main/res/layout/item_list_dogs.xml
> +        android:layout_marginStart="10dp"
16dp
https://material.io/design/layout/spacing-methods.html

2020-04-08 22:04 UTC, jmcaldera commented on app/src/main/res/layout/item_list_dogs.xml
> +        android:id="@+id/textView"
Asigna un id que indique lo que muestra este textView. Por ejemplo: label_add_fav

2020-04-15 19:29 UTC, cvalera18 commented on app/src/main/res/layout/item_list_dogs.xml
> +        android:layout_width="wrap_content"
Si le coloco el 0dp no me muestra ninguna imagen.

2020-04-15 20:57 UTC, jmcaldera approved these changes

2020-04-15 21:04 UTC, merged